[package]
name = "integer-partitions"
description = "Efficiently enumerate integer partitions."
repository = "https://github.com/quadrupleslap/integer-partitions"
keywords = ["integer", "partition"]
license = "MIT"
version = "0.1.0"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]
